/**
* Class Name    : RE_SendSMSInterface
* Owner         : DELOITTE
* Created Date  : 08/27/2019
* Description   : 
*
*                            M O D I F I C A T I O N   L O G                                          
*
*  Date        Developer       Description                                                         
*  ----------  -----------     -------------------------------------------------------------------
*  08/27/2019  LAGAN       Initial Version
*  
**/
public interface RE_SendSMSInterface {
    String executeSMSProcess(Map<String,String> parameterMap);

}