/**
* Class Name    : RE_URLShortnerResponseWrapper
* Owner         : DELOITTE
* Created Date  : 07/10/2019
* Description   : 
*
*                            M O D I F I C A T I O N   L O G                                          
*
*  Date        Developer       Description                                                         
*  ----------  -----------     -------------------------------------------------------------------
*  07/10/2019  Abhijeet       Initial Version
*  
**/
public class RE_URLShortnerResponseWrapper {
    
     public String url;
    
   /* public List<Response> Response;
    
    public class Response{
        public List<Data> data;  
    }
    
    public class Data{
        public String global_hash;
        public String hash;
        public String long_url;
        public String new_hash;
        public String url;
    }*/
}