@isTest
public class schemasMicrosoftCom200310SerializatTest {
    /********************************************************************************************
    * @author       CHFS Team
    * @date         5/11/2020
    * @methodname   
    * @description  
    * @param        none
    * @return       none
    ********************************************************************************************/
   static testMethod void test_ArrayOfstring(){
    schemasMicrosoftCom200310Serializat obj = new schemasMicrosoftCom200310Serializat();
    schemasMicrosoftCom200310Serializat.ArrayOfstring aryObj = new schemasMicrosoftCom200310Serializat.ArrayOfstring();
  }
}