/*
* Classname 	:  SSP_AVSTempuriOrgImports
* @description 	:  This class is a stub class for AVS
* @author 		:  Rijia Khatun
* @date 		:  02/07/2020
* MODIFICATION LOG:
* DEVELOPER                     DATE                               DESCRIPTION
* ---------------------------------------------------------------------------------------------
* DeveloperName	      MM/DD/YYYY	      A Brief Description 
						       about the Change
**/

public class SSP_AVSTempuriOrgImports {
}