/*
* Classname 	:  SSP_AVSMicrosoftComMessage
* @description 	:  This class is a stub class for AVS
* @author 		:  Rijia Khatun
* @date 		:  02/07/2020
* MODIFICATION LOG:
* DEVELOPER                     DATE                               DESCRIPTION
* ---------------------------------------------------------------------------------------------
* DeveloperName	      MM/DD/YYYY	      A Brief Description 
						       about the Change
**/

public class SSP_AVSMicrosoftComMessage {
    public class MessageBody {
        private String[] apex_schema_type_info = new String[]{'http://schemas.microsoft.com/Message','true','false'};
        private String[] field_order_type_info = new String[]{};
    }
}