/*
* Classname     :  SSP_RSSPDC_IntegrationDMLUtilityTest
* @description  :  This class is the test class of SSP_RSSPDC_IntegrationDMLUtility
* @author       :  Ragunathan
* @date         :  04/06/2020
* MODIFICATION LOG:
* DEVELOPER                     DATE                               DESCRIPTION
* ---------------------------------------------------------------------------------------------
* DeveloperName       MM/DD/YYYY          A Brief Description about the Change
* Ragunathan          04/06/2020            Initial Creation
**/
@isTest
public class SSP_RSSPDC_IntegrationDMLUtilityTest {
}
