/**
* Class Name    : SSP_AddressResponseWrapper
* Owner         : DELOITTE
* Created Date  : 11/12/2019
* Description   : Class that holds request for SSP_AddressVerification_IntUtility
*
*                            M O D I F I C A T I O N   L O G                                          
*
*  Date        Developer          			Description                                                         
*  ----------  -------------------------   -------------------------------------------------------------------
*  11/12/2019  Kommana Lova Durga Prasad   Initial Version
*/
public class SSP_AddressResponseWrapper {
    
    public boolean Issucess;
    public object ResponseDetail;
    public List<LOG_LogMessage__c> lstofLogMessages;

}