/*
* Classname 	:  SSP_TMemberStubClass
* @description 	:  This class is a stub class for TMember
* @author 		:  Rijia Khatun
* @date 		:  01/7/2019
* MODIFICATION LOG:
* DEVELOPER                     DATE                               DESCRIPTION
* ---------------------------------------------------------------------------------------------
* DeveloperName	      MM/DD/YYYY	      A Brief Description 
						       about the Change
**/

public class SSP_TMemberStubClass {
    public class ArrayOfint {
        public Integer[] int_x;
        private String[] int_x_type_info = new String[]{'int','http://schemas.microsoft.com/2003/10/Serialization/Arrays',null,'0','-1','false'};
        private String[] apex_schema_type_info = new String[]{'http://schemas.microsoft.com/2003/10/Serialization/Arrays','true','false'};
        private String[] field_order_type_info = new String[]{'int_x'};
    }
}