/*
 * Classname     :  SSP_MCIForBenefitRequestWrapper
 * @description  :  This class will hold the information for Request MCI Benefit Service
 * @author       :  Ragunathan
 * @date         :  06/04/2020
 * MODIFICATION LOG:
 * DEVELOPER                     DATE                               DESCRIPTION
 * ---------------------------------------------------------------------------------------------
 * DeveloperName       MM/DD/YYYY          A Brief Description about the Change
 * Ragunathan		   06/04/2020			Initial Creation
 **/
public class SSP_MCIForBenefitRequestWrapper {

    public Contact con;
    
    public SSP_MCIForBenefitRequestWrapper(){
        
    }
}