/*
* Classname         :  SSP_ContactInfoMockClass
* @description  :  This class is to mock the response for Adhoc SSP DC MyInformation
* @author       :  Rajeev Kumar
* @date         :  06/03/2019
* MODIFICATION LOG:
* DEVELOPER                     DATE                               DESCRIPTION
* ---------------------------------------------------------------------------------------------
* DeveloperName       MM/DD/YYYY          A Brief Description 
                               about the Change
**/
@isTest

public class SSP_ContactInfoMockClass {

}