public with sharing class SSP_TaxFormsCorrespondenceReqWrapper {
    // public attributes
    public TaxFormsCorrespondenceRequestParametersWrapper TaxFormsCorrespondenceRequestParameters;
    
    /**
     * 
     */
    public Class TaxFormsCorrespondenceRequestParametersWrapper {
        //public Attributes
        public String EnrollmentId;
        public String ApplicableYear;
        public String SourceApplication;
        public String UserInfo;
    }
    public SSP_TaxFormsCorrespondenceReqWrapper() {

    }
}